{
 "title": "Fraud & AML - Ops Dashboard",
 "tags": [
  "fraud",
  "aml",
  "bank"
 ],
 "refresh": "10s",
 "panels": [
  {
   "title": "Kafka Events Processed (rate)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "rate(kafka_events_processed_total[1m])",
     "legendFormat": "events/sec"
    }
   ]
  },
  {
   "title": "Alerts Created (rate) by type",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum by (type) (rate(fraud_alerts_total[1m]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Alerts by severity (rate)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum by (severity) (rate(fraud_alerts_total[1m]))",
     "legendFormat": "{{severity}}"
    }
   ]
  },
  {
   "title": "Cases Opened (rate) by priority",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum by (priority) (rate(fraud_cases_opened_total[1m]))",
     "legendFormat": "{{priority}}"
    }
   ]
  },
  {
   "title": "Credit Blocks Executed (rate)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 16, "w": 24, "h": 8 },
   "targets": [
    {
     "expr": "sum(rate(credit_blocks_total[1m]))",
     "legendFormat": "blocks/sec"
    }
   ]
  }
 ]
}